version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    # versioning-strategy: "increase-if-necessary" # Not yet supported. See <https://github.com/dependabot/dependabot-core/issues/4009>.
    assignees:
      - "Tamschi"

  - package-ecosystem: "cargo"
    directory: "/proc-macro-definitions/"
    schedule:
      interval: "daily"
    # versioning-strategy: "increase-if-necessary" # Not yet supported. See <https://github.com/dependabot/dependabot-core/issues/4009>.
    assignees:
      - "Tamschi"

  - package-ecosystem: "cargo"
    directory: "/book/"
    schedule:
      interval: "daily"
    # versioning-strategy: "increase-if-necessary" # Not yet supported. See <https://github.com/dependabot/dependabot-core/issues/4009>.
    assignees:
      - "Tamschi"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Tamschi"
