language: rust
rust:
  - 1.46.0
  - stable
  - beta
  - nightly
stages:
  - ensure format
#TODO: Disallow warnings again once features are simplified.
#  - deny warnings
  - test
  - deploy book
script:
  - cat CI.toml >> Cargo.toml
  - cargo +$TRAVIS_RUST_VERSION test
  - cargo +$TRAVIS_RUST_VERSION test --features services
  - cargo +$TRAVIS_RUST_VERSION test --features topiary
  - cargo +$TRAVIS_RUST_VERSION test --features "services topiary"
  - cd proc-macro-definitions && cargo +$TRAVIS_RUST_VERSION test && cd ..
  - cd book && cargo +$TRAVIS_RUST_VERSION test && cd ..
jobs:
  include:
    - stage: ensure format
      if: branch = develop
      script:
        - rustup toolchain install nightly --profile minimal --component rustfmt
        - cargo +nightly fmt -- --check
        - cd proc-macro-definitions
        - cargo +nightly fmt -- --check
        - cd ../book
        - cargo +nightly fmt -- --check
#    - stage: deny warnings
#      if: branch = develop
#      script:
#        - rustup component add clippy
#        - RUSTFLAGS='-D warnings' cargo build --all-targets
    - stage: deploy book
      if: branch = develop
      script:
        - cat CI.toml >> Cargo.toml
        - cd book && cargo +$TRAVIS_RUST_VERSION run && cd ..
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: book/book
        keep-history: true
        on:
          branch: develop
  allow_failures:
    - rust: nightly
  fast_finish: true
# cache: cargo # The build currently hangs on cache restore. Might fix itself once the features are simplified.
