[package]
name = "asteracea"
version = "0.0.1"
authors = ["Tamme Schichler <tamme@schichler.dev>"]
edition = "2018"
description = "A web application framework for Rust. Asteracea can be used for client-side and server-side rendering and for statically rendered and deployed sites (and combinations thereof) without specific changes to an app's code."
license = "MIT OR Apache-2.0"
repository = "https://github.com/Tamschi/Asteracea"
homepage = "https://github.com/Tamschi/Asteracea/tree/v0.0.1"
documentation = "https://docs.rs/asteracea/0.0.1"
keywords = ["framework", "server-side", "client-side", "static-site"]
categories = ["web-programming", "gui", "wasm", "no-std"]
readme = "README.md"
include = [
	"**/*.rs",
	"!tests/unincluded_*.rs", # Tests of meta data files not included in the package.
	"Cargo.toml",
	"CHANGELOG.md",
	"CODE_OF_CONDUCT.md",
	"LICENSE-*",
	"README.md",
]
publish = false

[badges]
travis-ci = { repository = "Tamschi/Asteracea", branch = "develop" }
is-it-maintained-issue-resolution = { repository = "Tamschi/Asteracea" }
is-it-maintained-open-issues = { repository = "Tamschi/Asteracea" }
maintenance = { status = "experimental" }

[features]
# Enables dependency extraction with component!.
rhizome = ["rhizome_crate", "asteracea_proc-macro-definitions/rhizome"]
# Enables "rhizome/macros".
rhizome_macros = ["rhizome", "rhizome_crate/macros"]
services = ["rhizome_macros"]
styles = ["rhizome_macros"]
topiary = [
    "styles",
    "topiary_crate",
    "asteracea_proc-macro-definitions/rhizome",
    "asteracea_proc-macro-definitions/styles",
]

[dependencies]
asteracea_proc-macro-definitions = { path = "proc-macro-definitions" }
lazy_static = "1.4.0"
lignin-schema = { version = "0.0.1", features = ["bumpalo-collections"] }
rhizome_crate = { package = "rhizome", version = "0.0.1", optional = true }
topiary_crate = { package = "topiary", version = "0.0.1", optional = true }

[dev-dependencies]
cargo-husky = "1.5.0"
doc-comment = "0.3.3"
git_info = "0.1.2"
version-sync = "0.9.1"
lignin = "0.0.1"
