name: Weekly Audit

permissions:
  contents: read
  issues: write

on:
  schedule:
    #FIXME: Schedule this daily but make it so that the job doesn't fail no matter what.
    # (New advisories still get reported as issues, anyway.)
    - cron: '* 23 * * 5'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
